#spring:
#  datasource:
#    url: jdbc:postgresql://172.16.0.119:5434/trainee?useUnicode=true&characterEncoding=UTF-8
#    username: smt
#    password: SmtP@ssw0rd1234
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#      hibernate.jdbc.lob.non_contextual_creation: true
#    hibernate:
#      ddl-auto: update

#spring:
#                  datasource:
#                    url: jdbc:postgresql://172.16.0.119:5434/trainee
#                    username: trainee
#                    password: trainee_12345
#                  jpa:
#                    show-sql: true
#                    properties:
#                      hibernate.id.new_generator_mappings: true
#                      hibernate.cache.use_second_level_cache: false
#                      hibernate.cache.use_query_cache: false
#                      hibernate.generate_statistics: true
#                      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#                      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#                      hibernate.jdbc.lob.non_contextual_creation: true
#                    hibernate:
#                      ddl-auto: update

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update